workflows:
  default-workflow:
    name: Default Workflow
    environment:
      # إصدار فلاتر الذي سيستخدمه Codemagic.
      flutter: stable
      # إصدار Xcode الذي تحتاجه لبناء تطبيقات iOS.
      xcode: latest
    
    scripts:
      - |
        # تثبيت حزم فلاتر (packages) للمشروع.
        echo "Installing Flutter dependencies..."
        cd customer
        flutter pub get
      - |
        # بناء تطبيق iOS بصيغة IPA
        echo "Building iOS IPA..."
        cd customer
        flutter build ios --release --no-codesign

    artifacts:
      # تحديد مكان ملفات IPA التي تم بناؤها.
      - customer/build/ios/ipa/*.ipa

    publishing:
      # إعدادات النشر
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
