    workflows:
      default-workflow:
        name: Default Workflow
        environment:
          flutter: stable
          xcode: latest
          jdk: 17
        scripts:
          - |
            echo "Installing Flutter dependencies..."
            cd customer
            flutter pub get
          - |
            echo "Building Android APK..."
            cd customer
            flutter build apk --release
        artifacts:
          - customer/build/app/outputs/apk/release/*.apk
        publishing:
          email:
            recipients:
              - your-email@example.com
            notify:
              success: true
              failure: false
    