// This file is auto-generated by the Firebase CLI.
// To update these options, run:
// `flutterfire configure`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmECA4zV55URY4mT7kaOKDHWCvlBDWom0',
    appId: '1:78317324117:web:2490d6482baebb9a8711dc',
    messagingSenderId: '78317324117',
    projectId: 'alhayekjewelry-7ff5e',
    authDomain: 'alhayekjewelry-7ff5e.firebaseapp.com',
    storageBucket: 'alhayekjewelry-7ff5e.firebasestorage.app',
    measurementId: 'G-EWT1PQ4Q4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMn0sc0hEhH985nmSV69vXVMrMs-rDSR4',
    appId: '1:78317324117:android:997407bf64f8254c8711dc',
    messagingSenderId: '78317324117',
    projectId: 'alhayekjewelry-7ff5e',
    storageBucket: 'alhayekjewelry-7ff5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGOkUmwXn81g8GLrTMpIf2WnXIHU-OELM',
    appId: '1:78317324117:ios:56cecfa2c378fb9a8711dc',
    messagingSenderId: '78317324117',
    projectId: 'alhayekjewelry-7ff5e',
    storageBucket: 'alhayekjewelry-7ff5e.firebasestorage.app',
    iosBundleId: 'com.example.newhayekjewel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGOkUmwXn81g8GLrTMpIf2WnXIHU-OELM',
    appId: '1:78317324117:ios:56cecfa2c378fb9a8711dc',
    messagingSenderId: '78317324117',
    projectId: 'alhayekjewelry-7ff5e',
    storageBucket: 'alhayekjewelry-7ff5e.firebasestorage.app',
    iosBundleId: 'com.example.newhayekjewel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmECA4zV55URY4mT7kaOKDHWCvlBDWom0',
    appId: '1:78317324117:web:d5552b2de747db488711dc',
    messagingSenderId: '78317324117',
    projectId: 'alhayekjewelry-7ff5e',
    authDomain: 'alhayekjewelry-7ff5e.firebaseapp.com',
    storageBucket: 'alhayekjewelry-7ff5e.firebasestorage.app',
    measurementId: 'G-K7RN5R7TYC',
  );

}